### ISSUE TITLE
Switch to implementing pasts' `Notifier` instead of implementing `Future`

### ISSUE THREAD

**Issue by AldaronLau** [libcala/human#2]

**Comment by adaburton** [comment]
Hey,

Is there any more in depth documentation on how to implement the Notifier properly for different situations? I think I have successfully implemented Notified for the controller, but I'm having some difficulty implementing it for the InputListener. The compiler still wants me to implement Future, even though I have removed all mentions of it from the document. I suspect the compiler is inferring the trait somewhere but I am not familiar enough with the module to figure out where.

**Comment by adaburton** [comment]
![Screenshot from 2022-07-11 15-50-03](https://user-images.githubusercontent.com/94191498/178371846-c2041bbd-a85d-49b9-ae9c-97562a1bfde8.png)
here is the error,

...and the code
![Screenshot from 2022-07-11 15-55-26](https://user-images.githubusercontent.com/94191498/178372390-d3453c4a-3693-4699-8425-195f4f52ffd9.png)

**Comment by AldaronLau** [comment]
You can't change the generic on `InputListener` from `T: Future` to `T: Notifier` because stick hasn't been updated to use `Notifier` yet.

**Comment by adaburton** [comment]
Okay, in that case, I'll work on updating stick today

**Comment by adaburton** [comment]
I noticed that there is a branch in stick that at least depends on an older version of pasts. How should I proceed?

**Comment by AldaronLau** [comment]
You shouldn't need to update stick to get human to work.  But, if you want to work on stick, base it off https://github.com/libcala/stick/pull/50 instead of main.

**Comment by adaburton** [comment]
I see. How should I go about implementing the notifier without updating stick? Should I leave the generic alone, and then implement the Notifier separately? Currently, if I leave the generic as a Future, and attempt to implement the Notifier, the compiler complains that I'm not using a Future type everywhere I define a Notifier.

**Comment by adaburton** [comment]
It's actually complaining about the placeholder T here: 
`impl<T> Notifier for InputListener<T>
where
    T: Notifier + Unpin,
{`

**Comment by AldaronLau** [comment]
You should be able to get it to work with `impl<T> Notifier for InputListener<T> where T: Future + Unpin, {`

**Comment by adaburton** [comment]
When calling Poll::Ready it still wants a future::Output type rather than pasts::Event because the associated type is Future. Should I used a different method to check for new input?

**Comment by AldaronLau** [comment]
You should be able to call `T::poll()` in `poll_next()` and have `type Event = <T as Future>::Output` on `InputListener`.

**Comment by adaburton** [comment]
I apologize for being so needy, I have never done any work with asynchronous computing before, but at least I'm learning alot!
The compiler is not liking T::poll(), thinks its a pattern. Should I just get rid of the check? I'm also unclear on what exactly the function is trying to achieve. 

As far as I can tell, we are adding functionality to set up input processing while the program is running. the poll_next function will ask first whether there is a new input device/controller plugged in, and if so, will return that it is ready. Otherwise, it will return the pending status. 

Am I on the right track?

**Comment by AldaronLau** [comment]
> I apologize for being so needy, I have never done any work with asynchronous computing before, but at least I'm learning alot!

NP!

> The compiler is not liking T::poll(), thinks its a pattern. Should I just get rid of the check? I'm also unclear on what exactly the function is trying to achieve.

Never mind about `T::poll()`, I was thinking about implementing `Notifier` for `Controller`.  Sorry about that.

> As far as I can tell, we are adding functionality to set up input processing while the program is running. the poll_next function will ask first whether there is a new input device/controller plugged in, and if so, will return that it is ready. Otherwise, it will return the pending status.

Yeah, that's how it works.

**Comment by adaburton** [comment]
Ah, that makes sense, so any advice on reconciling Poll::Ready() and Pin::new? Poll::ready is evaluating to Input, where Pin evaluates to Future::Output. Also, in the body of the if statement, the compiler is confused that we are feeding an Input into Ready. I guess Input isn't the associated type of the function?

My guess is that this is because we are implementing Notifier for InputListener<Future + Unpin> but I'm not sure.

**Comment by adaburton** [comment]
If it would be easier, I can send you another screenshot of where I am at.

**Comment by AldaronLau** [comment]
Yeah, a screenshot of the error and the code would help.

**Comment by adaburton** [comment]
Here

![Screenshot from 2022-07-12 14-45-59](https://user-images.githubusercontent.com/94191498/178601453-6e6f5cb2-08dd-4d0b-b09b-e2a99f3658b7.png)
![Screenshot from 2022-07-11 15-55-26](https://user-images.githubusercontent.com/94191498/178601471-4a0b98de-e287-4688-89b4-8a893363b7b8.png)

**Comment by adaburton** [comment]
Sorry about that

![Screenshot from 2022-07-12 14-45-59](https://user-images.githubusercontent.com/94191498/178601696-27732bd1-b661-40ea-b4bb-5eb29c756fc4.png)
![Screenshot from 2022-07-12 14-48-58](https://user-images.githubusercontent.com/94191498/178601716-ef049c33-5061-4a55-8465-76254f45d544.png)

**Comment by AldaronLau** [comment]
I told you the wrong thing, because of was thinking of the impl of `Notifier` on `Controller` again (sorry again).  It should be `Event = Input`.

**Comment by adaburton** [comment]
I see! that seems to have cleared up the second error, but there is still the mismatch between Ready and poll, where Ready is returning an Input, and poll is returning an Output. should I be using a different namespace than Pin?

**Comment by AldaronLau** [comment]
Hmm, what if you change the `where` clause to:

```rust
where
    T: Future<Output = Input> + Unpin
```

**Comment by adaburton** [comment]
That seems to fix it, the final thing I'm getting issues with is implementing Input. Specifically the return type for the listener function.

**Comment by AldaronLau** [comment]
I believe it should be `impl Notifier<Event = Input>`

**Comment by adaburton** [comment]
It wants a tuple where Input is

**Comment by adaburton** [comment]
I'm assuming something like (type, Input). just don't know what to put where type is

**Comment by AldaronLau** [comment]
I think I know what's going on.

https://github.com/ardaku/human/blob/stable/src/input.rs#L87-L100, the where clause and if let statement need to be reverted back to what they used to be to account for the tuple.

**Comment by adaburton** [comment]
aha! that seems to have done the trick! submitting for review..
